import fs from "node:fs";
import path from "node:path";
import yaml from "js-yaml";
import { loadConfig } from "./config.js";
import { parse } from "./parser.js";
import { resolve } from "./resolver.js";
import { resolveTemplates } from "./template.js";
import type { CompileResult, CompiledWorkflow, CompileError } from "./types.js";
import { GhacError } from "./errors.js";

function collectWorkflowFiles(dir: string, prefix: string = ""): { relativePath: string; absolutePath: string }[] {
  const results: { relativePath: string; absolutePath: string }[] = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    const abs = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      results.push(...collectWorkflowFiles(abs, rel));
    } else if (entry.name.endsWith(".yml") || entry.name.endsWith(".yaml")) {
      results.push({ relativePath: rel, absolutePath: abs });
    }
  }

  return results;
}

function flattenName(relativePath: string, mode: "prefix" | "flat"): string {
  if (mode === "flat" || !relativePath.includes("/")) {
    // Just use the filename
    return path.basename(relativePath);
  }
  // prefix mode: deploy/staging-auto.yml → deploy-staging-auto.yml
  return relativePath.replace(/\//g, "-");
}

export function compile(projectRoot: string): CompileResult {
  const config = loadConfig(projectRoot);
  const sourceDir = path.resolve(projectRoot, config.source);
  const workflowsDir = path.join(sourceDir, "workflows");

  const workflows: CompiledWorkflow[] = [];
  const errors: CompileError[] = [];

  if (!fs.existsSync(workflowsDir)) {
    errors.push({
      file: workflowsDir,
      message: `Workflows directory not found: ${workflowsDir}`,
    });
    return { workflows, errors };
  }

  const files = collectWorkflowFiles(workflowsDir);

  for (const file of files) {
    const sourcePath = `workflows/${file.relativePath}`;
    const outputName = flattenName(file.relativePath, config.flatten);

    try {
      const raw = fs.readFileSync(file.absolutePath, "utf-8");
      const parsed = parse(raw);
      const resolved = resolve(parsed, sourceDir);
      const templated = resolveTemplates(resolved, sourceDir);

      const outputYaml = yaml.dump(templated, {
        lineWidth: 120,
        noRefs: true,
        quotingType: '"',
      });

      const header = `# Auto-generated by ghac — do not edit directly\n# Source: ${config.source}/${sourcePath}\n\n`;

      workflows.push({
        sourcePath,
        outputName,
        content: header + outputYaml,
      });
    } catch (err) {
      errors.push({
        file: sourcePath,
        message: err instanceof GhacError ? err.message : String(err),
      });
    }
  }

  return { workflows, errors };
}

export function build(projectRoot: string): CompileResult {
  const config = loadConfig(projectRoot);
  const outputDir = path.resolve(projectRoot, config.output);
  const result = compile(projectRoot);

  if (result.errors.length > 0) {
    for (const error of result.errors) {
      console.error(`ERROR: ${error.file}: ${error.message}`);
    }
    return result;
  }

  fs.mkdirSync(outputDir, { recursive: true });

  for (const workflow of result.workflows) {
    const outputPath = path.join(outputDir, workflow.outputName);
    fs.writeFileSync(outputPath, workflow.content, "utf-8");
    console.log(`  ${workflow.sourcePath} → ${config.output}/${workflow.outputName}`);
  }

  return result;
}
